import React, { useEffect, useMemo, useState } from 'react';
import { Activity, Bot, Box, ChevronRight, CircleGauge, Cpu, ExternalLink, Gauge, HardDrive, Home, Info, MemoryStick, Mic, Newspaper, PackageSearch, PlaneLanding, Radio, RefreshCw, RotateCcw, Save, Search, Settings, ShieldAlert, Ship, Sparkles, Square, WandSparkles, Zap } from 'lucide-react';
import { api, hasDesktopBridge } from './lib/api.js';

const nav = [
  ['Command Deck', Home], ['Assistant', Bot], ['News', Newspaper], ['FleetYards', Ship], ['Marketplace', PackageSearch], ['Optimizer', Gauge], ['Settings', Settings]
];
const greenBtn='bg-emerald-400 text-black hover:bg-emerald-300 disabled:opacity-40 disabled:cursor-not-allowed transition font-semibold';
const ghostBtn='border border-emerald-300/15 bg-emerald-300/[.04] hover:bg-emerald-300/[.08] text-emerald-100 transition';

function Badge({children, tone='green'}) { const c=tone==='amber'?'border-amber-300/25 bg-amber-300/10 text-amber-200':tone==='red'?'border-red-300/25 bg-red-300/10 text-red-200':'border-emerald-300/25 bg-emerald-300/10 text-emerald-200'; return <span className={`inline-flex items-center rounded-full border px-2.5 py-1 text-[11px] tracking-widest uppercase ${c}`}>{children}</span> }
function Card({children,className=''}) { return <div className={`hud-card rounded-xl ${className}`}>{children}</div> }
function Empty({children}) { return <div className="rounded-lg border border-dashed border-emerald-200/15 p-8 text-center text-sm text-white/45">{children}</div> }
function Open({url, children}) { return <button onClick={()=>api.openExternal(url)} className="inline-flex items-center gap-1.5 text-emerald-300 hover:text-emerald-200">{children}<ExternalLink size={13}/></button> }

export default function App(){
  const [page,setPage]=useState('Command Deck'); const [boot,setBoot]=useState(null); const [busy,setBusy]=useState(true); const [toast,setToast]=useState('');
  const [voiceOn,setVoiceOn]=useState(false); const [voiceEvent,setVoiceEvent]=useState(null); const [chat,setChat]=useState([{who:'ai',text:'NekoVerse flight systems ready. Say “Neko, request landing” after you configure the matching ATC hotkey.'}]);
  const [message,setMessage]=useState(''); const [fleetQ,setFleetQ]=useState('Carrack'); const [fleet,setFleet]=useState(null); const [marketQ,setMarketQ]=useState('Carrack'); const [market,setMarket]=useState(null); const [lti,setLti]=useState(true);
  const [settings,setSettings]=useState(null);

  useEffect(()=>{(async()=>{ if(!hasDesktopBridge()){setBusy(false);return;} try{const b=await api.bootstrap();setBoot(b);setSettings(b.settings);}catch(e){notice(e.message)}finally{setBusy(false)}})(); const off=api.onVoice?.(e=>{setVoiceEvent(e);setChat(c=>[...c,{who:'user',text:e.recognized},{who:'ai',text:e.actionResult?.error?`${e.reply.text} ${e.actionResult.error}`:e.reply.text}]);}); return()=>off?.()},[]);
  function notice(t){setToast(String(t));setTimeout(()=>setToast(''),4200)}
  async function refreshStatus(){const status=await api.refreshStatus();setBoot(b=>({...b,status}));notice('Live/PTU status refreshed')}
  async function toggleVoice(){const r=voiceOn?await api.voiceStop():await api.voiceStart(); if(r?.ok){setVoiceOn(!voiceOn);notice(!voiceOn?'Voice listening enabled':'Voice listening stopped')} else notice(r?.error||'Voice action failed')}
  async function sendAssistant(){const q=message.trim();if(!q)return;setMessage('');setChat(c=>[...c,{who:'user',text:q}]);const r=await api.assistantAsk(q);setChat(c=>[...c,{who:'ai',text:r?.actionResult?.error?`${r.reply.text} ${r.actionResult.error}`:r?.reply?.text||'No response'}])}
  async function fleetSearch(){setFleet({loading:true});setFleet(await api.searchFleet(fleetQ))}
  async function marketSearch(){setMarket({loading:true});setMarket(await api.searchMarket(marketQ,lti))}
  async function rescan(){const o=await api.analyzeHardware();setBoot(b=>({...b,optimizer:o}));notice('Hardware scan complete')}
  async function applyOpt(){const r=await api.applyOptimization(boot?.optimizer?.recommended);notice(r?.ok?`Safe profile applied. Backup: ${r.backup}`:r?.error||'Could not apply')}
  async function restoreOpt(){const r=await api.restoreOptimization();notice(r?.ok?'Latest NekoVerse backup restored':r?.error||'Could not restore')}
  async function save(){const s=await api.saveSettings(settings);setSettings(s);notice('Settings saved')}
  async function run(cmd){const r=await api.hotkeyRun(cmd);notice(r?.ok?`Sent ${r.combo}`:r?.error||'Command failed')}

  const status=boot?.status; const opt=boot?.optimizer; const hw=opt?.hardware; const rec=opt?.recommended;
  const content={
    'Command Deck': <div className="space-y-5">
      <div className="grid grid-cols-12 gap-4">
        <Card className="col-span-8 p-6 scanline"><div className="flex items-start justify-between"><div><div className="text-xs tracking-[.32em] text-emerald-300/65">VERSE NETWORK</div><h2 className="mt-2 text-3xl font-light text-white">Flight Command Deck</h2><p className="mt-2 max-w-xl text-sm text-white/48">News, build status, ship research, voice actions and your local performance profile in one cockpit-friendly desktop companion.</p></div><Radio className="text-emerald-300"/></div><div className="mt-8 grid grid-cols-3 gap-3">
          <div className="rounded-lg border border-white/6 bg-black/20 p-4"><div className="text-[10px] tracking-[.25em] text-white/35">LIVE</div><div className="mt-2 text-xl text-emerald-300 glow">{status?.live||'—'}</div><div className="mt-1 text-xs text-white/36">{status?.liveBuild||'Official status adapter'}</div></div>
          <div className="rounded-lg border border-white/6 bg-black/20 p-4"><div className="text-[10px] tracking-[.25em] text-white/35">PTU</div><div className="mt-2 text-xl text-white">{status?.ptu||'—'}</div><div className="mt-1 text-xs text-white/36">{status?.stale?'cached fallback':'live check'}</div></div>
          <div className="rounded-lg border border-white/6 bg-black/20 p-4"><div className="text-[10px] tracking-[.25em] text-white/35">PROFILE</div><div className="mt-2 text-xl capitalize text-white">{rec?.tier||'—'}</div><div className="mt-1 text-xs text-white/36">{hw?.gpu||'Hardware not scanned'}</div></div>
        </div><div className="mt-5 flex gap-2"><button onClick={refreshStatus} className={`rounded-lg px-3.5 py-2 text-sm ${ghostBtn}`}><RefreshCw size={14} className="mr-2 inline"/>Refresh network</button><button onClick={()=>setPage('Optimizer')} className={`rounded-lg px-3.5 py-2 text-sm ${greenBtn}`}><WandSparkles size={14} className="mr-2 inline"/>Optimize my PC</button></div></Card>
        <Card className="col-span-4 p-5"><div className="flex items-center justify-between"><div><div className="text-xs tracking-[.28em] text-emerald-300/65">VOICE CORE</div><div className="mt-1 text-xl">Neko Assistant</div></div><Bot className="text-emerald-300"/></div><div className="mt-5 rounded-xl border border-emerald-300/10 bg-emerald-300/[.03] p-4"><div className="flex items-center gap-2"><span className={`h-2.5 w-2.5 rounded-full ${voiceOn?'bg-emerald-300 shadow-[0_0_14px_rgba(110,255,170,.8)]':'bg-white/20'}`}/><span className="text-sm text-white/70">{voiceOn?'Listening for wake word':'Voice standby'}</span></div><div className="mt-3 text-xs text-white/38">Try: “Neko, request landing”</div></div><button onClick={toggleVoice} className={`mt-4 w-full rounded-lg px-4 py-3 ${voiceOn?ghostBtn:greenBtn}`}>{voiceOn?<><Square size={15} className="mr-2 inline"/>Stop listener</>:<><Mic size={15} className="mr-2 inline"/>Activate voice</>}</button><button onClick={()=>run('request_landing')} className={`mt-2 w-full rounded-lg px-4 py-2.5 text-sm ${ghostBtn}`}><PlaneLanding size={15} className="mr-2 inline"/>Request landing hotkey</button>{voiceEvent&&<div className="mt-4 text-xs text-white/45">Last heard: <span className="text-emerald-200">{voiceEvent.recognized}</span></div>}</Card>
      </div>
      <div className="grid grid-cols-3 gap-4"><Card className="p-5"><Cpu className="text-emerald-300" size={20}/><div className="mt-3 text-xs text-white/35">CPU</div><div className="mt-1 line-clamp-2 text-sm text-white/80">{hw?.cpu||'Scan hardware'}</div></Card><Card className="p-5"><Activity className="text-emerald-300" size={20}/><div className="mt-3 text-xs text-white/35">GPU</div><div className="mt-1 line-clamp-2 text-sm text-white/80">{hw?.gpu||'Scan hardware'}</div></Card><Card className="p-5"><MemoryStick className="text-emerald-300" size={20}/><div className="mt-3 text-xs text-white/35">MEMORY</div><div className="mt-1 text-sm text-white/80">{hw?`${hw.ramGB} GB RAM${hw.vramGB?` • ${hw.vramGB} GB VRAM`:''}`:'Scan hardware'}</div></Card></div>
    </div>,
    'Assistant': <div className="grid h-[calc(100vh-112px)] grid-cols-12 gap-4"><Card className="col-span-8 flex min-h-0 flex-col p-5"><div className="flex items-center justify-between border-b border-white/6 pb-4"><div><div className="text-xs tracking-[.25em] text-emerald-300/60">AI / COMMAND INTERFACE</div><div className="mt-1 text-xl">Neko Flight Assistant</div></div><button onClick={toggleVoice} className={`rounded-lg px-3 py-2 text-sm ${voiceOn?greenBtn:ghostBtn}`}><Mic size={14} className="mr-2 inline"/>{voiceOn?'Listening':'Voice off'}</button></div><div className="min-h-0 flex-1 space-y-3 overflow-auto py-5">{chat.map((m,i)=><div key={i} className={`max-w-[82%] rounded-xl border p-3.5 text-sm leading-relaxed ${m.who==='user'?'ml-auto border-emerald-300/20 bg-emerald-300/10 text-emerald-50':'border-white/7 bg-white/[.025] text-white/72'}`}>{m.text}</div>)}</div><div className="flex gap-2 border-t border-white/6 pt-4"><input value={message} onChange={e=>setMessage(e.target.value)} onKeyDown={e=>e.key==='Enter'&&sendAssistant()} placeholder="Ask Neko, or type a utility command…" className="flex-1 rounded-lg border border-emerald-300/15 bg-black/30 px-4 py-3 outline-none focus:border-emerald-300/45"/><button onClick={sendAssistant} className={`rounded-lg px-5 ${greenBtn}`}><ChevronRight/></button></div></Card><Card className="col-span-4 p-5"><div className="text-xs tracking-[.25em] text-emerald-300/60">ONE-SHOT ACTIONS</div><div className="mt-4 space-y-2">{Object.entries(settings?.commands||{}).map(([k,v])=><button key={k} onClick={()=>run(k)} className={`flex w-full items-center justify-between rounded-lg px-3 py-3 text-left text-sm ${ghostBtn}`}><span>{v.label}</span><span className="font-mono text-xs text-emerald-300/65">{v.combo||'UNBOUND'}</span></button>)}</div><div className="mt-5 rounded-lg border border-amber-300/15 bg-amber-300/5 p-3 text-xs leading-relaxed text-amber-100/65">Utility/accessibility hotkeys only. No combat automation, unattended macros, aim/recoil tools, or anti-cheat bypasses.</div></Card></div>,
    'News': <NewsPage boot={boot} setBoot={setBoot} notice={notice}/>,
    'FleetYards': <div className="space-y-4"><Card className="p-5"><div className="flex items-end gap-3"><div className="flex-1"><div className="text-xs tracking-[.25em] text-emerald-300/60">SHIP DATABASE</div><div className="mt-1 text-2xl">FleetYards integration</div><div className="mt-3 flex"><input value={fleetQ} onChange={e=>setFleetQ(e.target.value)} onKeyDown={e=>e.key==='Enter'&&fleetSearch()} className="w-full rounded-l-lg border border-emerald-300/15 bg-black/30 px-4 py-3 outline-none focus:border-emerald-300/45"/><button onClick={fleetSearch} className={`rounded-r-lg px-5 ${greenBtn}`}><Search/></button></div></div><Ship className="mb-2 text-emerald-300" size={34}/></div></Card>{fleet?.loading?<Empty>Searching FleetYards…</Empty>:fleet?.items?.length?<div className="grid grid-cols-2 gap-4">{fleet.items.map(s=><Card key={s.slug} className="p-5"><div className="flex justify-between"><div><div className="text-xs text-emerald-300/60">{s.manufacturer}</div><div className="mt-1 text-xl">{s.name}</div><div className="mt-2 text-sm text-white/45">{s.focus}</div></div><Box className="text-emerald-300/60"/></div><div className="mt-4 grid grid-cols-3 gap-2 text-xs"><div className="rounded-md bg-white/[.025] p-2"><span className="text-white/30">SIZE</span><br/>{String(s.size)}</div><div className="rounded-md bg-white/[.025] p-2"><span className="text-white/30">CREW</span><br/>{String(s.crew)}</div><div className="rounded-md bg-white/[.025] p-2"><span className="text-white/30">CARGO</span><br/>{String(s.cargo)}</div></div><div className="mt-4 text-sm"><Open url={s.url}>View on FleetYards</Open></div></Card>)}</div>:<Empty>{fleet?.error||'Search for a ship model to query FleetYards.'}</Empty>}</div>,
    'Marketplace': <div className="space-y-4"><Card className="p-5"><div className="flex items-center justify-between"><div><div className="text-xs tracking-[.25em] text-emerald-300/60">THIRD-PARTY MARKET SEARCH</div><div className="mt-1 text-2xl">Ship listing finder</div></div><ShieldAlert className="text-amber-300"/></div><div className="mt-4 rounded-lg border border-amber-300/20 bg-amber-300/[.06] p-3 text-sm leading-relaxed text-amber-100/70"><b className="text-amber-200">Grey-market warning:</b> third-party pledge trades are not CIG/RSI-supported purchases. NekoVerse does not label a seller “safe”, process payments, or handle account credentials. Verify insurance, item type, seller, escrow/refund terms and the final transfer yourself.</div><div className="mt-4 flex gap-2"><input value={marketQ} onChange={e=>setMarketQ(e.target.value)} onKeyDown={e=>e.key==='Enter'&&marketSearch()} className="flex-1 rounded-lg border border-emerald-300/15 bg-black/30 px-4 py-3 outline-none focus:border-emerald-300/45"/><label className="flex items-center gap-2 rounded-lg border border-white/7 px-3 text-sm text-white/65"><input type="checkbox" checked={lti} onChange={e=>setLti(e.target.checked)}/> LTI only</label><button onClick={marketSearch} className={`rounded-lg px-5 ${greenBtn}`}><Search/></button></div></Card>{market?.loading?<Empty>Searching public marketplace listings…</Empty>:market?.items?.length?<div className="grid grid-cols-2 gap-3">{market.items.map((x,i)=><Card key={x.url+i} className="p-4"><div className="flex items-start justify-between gap-3"><div><Badge tone={x.lti?'green':'amber'}>{x.lti?'LTI MATCH':'LISTING'}</Badge><div className="mt-3 font-medium text-white/85">{x.title}</div><div className="mt-2 text-sm text-white/45">{x.provider} • {x.price}</div></div><button onClick={()=>api.openExternal(x.url)} className="rounded-lg border border-white/8 p-2 text-emerald-300 hover:bg-white/5"><ExternalLink size={16}/></button></div></Card>)}</div>:<Empty>Deep-search public listings across Star Hangar, Space Foundry and The Impound.</Empty>}</div>,
    'Optimizer': <div className="space-y-4"><div className="grid grid-cols-12 gap-4"><Card className="col-span-7 p-5"><div className="flex justify-between"><div><div className="text-xs tracking-[.25em] text-emerald-300/60">HARDWARE TELEMETRY</div><div className="mt-1 text-2xl">Adaptive graphics profile</div></div><CircleGauge className="text-emerald-300"/></div><div className="mt-5 grid grid-cols-2 gap-3 text-sm"><Spec icon={Cpu} label="CPU" value={hw?.cpu}/><Spec icon={Activity} label="GPU" value={hw?.gpu}/><Spec icon={MemoryStick} label="RAM" value={hw?`${hw.ramGB} GB`:null}/><Spec icon={HardDrive} label="VRAM" value={hw?.vramGB?`${hw.vramGB} GB`:'Not reported'}/></div><div className="mt-4 flex gap-2"><button onClick={rescan} className={`rounded-lg px-4 py-2.5 text-sm ${ghostBtn}`}><RefreshCw size={14} className="mr-2 inline"/>Rescan</button><button onClick={applyOpt} className={`rounded-lg px-4 py-2.5 text-sm ${greenBtn}`}><Zap size={14} className="mr-2 inline"/>Apply safe renderer profile</button><button onClick={restoreOpt} className={`rounded-lg px-4 py-2.5 text-sm ${ghostBtn}`}><RotateCcw size={14} className="mr-2 inline"/>Restore backup</button></div></Card><Card className="col-span-5 p-5"><div className="text-xs tracking-[.25em] text-emerald-300/60">RECOMMENDATION</div><div className="mt-2 flex items-center gap-2"><Badge>{rec?.tier||'unknown'} profile</Badge></div><dl className="mt-5 space-y-3 text-sm"><Row k="Renderer" v={rec?.renderer}/><Row k="Upscaler" v={rec?`${rec.upscaler} • ${rec.upscalerQuality}`:null}/><Row k="Textures" v={rec?.texture}/><Row k="Clouds" v={rec?.clouds}/><Row k="Resolution" v={rec?.resolution}/></dl></Card></div><Card className="p-5"><div className="text-sm font-medium">What “automatic” changes</div><p className="mt-2 max-w-4xl text-sm leading-relaxed text-white/45">NekoVerse deliberately applies only the renderer setting in the local GraphicsSettings JSON and creates a timestamped backup. The remaining recommendations are shown for the in-game menu because undocumented CVars can change between patches and aggressive Windows tweaks often make Star Citizen less stable, not more.</p><div className="mt-3 text-xs text-white/35">Graphics file: {opt?.graphics?.file||'Not found yet'} • Install: {opt?.install?.root||'Not auto-detected'}</div></Card></div>,
    'Settings': settings?<div className="space-y-4"><Card className="p-5"><div className="flex justify-between"><div><div className="text-xs tracking-[.25em] text-emerald-300/60">VOICE & IDENTITY</div><div className="mt-1 text-2xl">Companion settings</div></div><Settings className="text-emerald-300"/></div><div className="mt-5 grid grid-cols-2 gap-4"><Field label="Wake words" value={(settings.wakeWords||[]).join(', ')} onChange={v=>setSettings(s=>({...s,wakeWords:v.split(',').map(x=>x.trim()).filter(Boolean)}))}/><Field label="Custom Star Citizen install path" value={settings.customInstallPath||''} onChange={v=>setSettings(s=>({...s,customInstallPath:v}))}/></div><div className="mt-4 flex gap-5 text-sm text-white/65"><Check label="Require wake word" value={settings.requireWakeWord} onChange={v=>setSettings(s=>({...s,requireWakeWord:v}))}/><Check label="Speak assistant replies" value={settings.speakReplies} onChange={v=>setSettings(s=>({...s,speakReplies:v}))}/></div></Card><Card className="p-5"><div className="text-sm font-medium">Utility hotkeys</div><p className="mt-1 text-xs text-white/38">Match these to your own Star Citizen bindings. Blank means disabled. Supported combos: A-Z, 0-9, F1-F12, Ctrl, Alt, Shift, Enter, Esc, Tab, Space.</p><div className="mt-4 grid grid-cols-2 gap-3">{Object.entries(settings.commands||{}).map(([k,v])=><Field key={k} label={v.label} value={v.combo||''} onChange={value=>setSettings(s=>({...s,commands:{...s.commands,[k]:{...s.commands[k],combo:value}}}))}/>)}</div></Card><Card className="p-5"><div className="flex items-center gap-2"><Sparkles className="text-emerald-300" size={18}/><div className="text-sm font-medium">Optional OpenAI-compatible local/cloud model</div></div><div className="mt-4 grid grid-cols-3 gap-3"><Field label="Base URL" value={settings.ai?.baseUrl||''} onChange={v=>setSettings(s=>({...s,ai:{...s.ai,baseUrl:v}}))}/><Field label="Model" value={settings.ai?.model||''} onChange={v=>setSettings(s=>({...s,ai:{...s.ai,model:v}}))}/><Field label="API key (optional)" type="password" value={settings.ai?.apiKey||''} onChange={v=>setSettings(s=>({...s,ai:{...s.ai,apiKey:v}}))}/></div><div className="mt-4"><Check label="Enable model endpoint" value={settings.ai?.enabled} onChange={v=>setSettings(s=>({...s,ai:{...s.ai,enabled:v}}))}/></div></Card><button onClick={save} className={`rounded-lg px-5 py-3 ${greenBtn}`}><Save size={15} className="mr-2 inline"/>Save all settings</button></div>:<Empty>Settings are loading…</Empty>
  }[page];

  return <div className="flex h-screen text-white"><aside className="w-[245px] shrink-0 border-r border-emerald-300/10 bg-[#050b08]/90 p-4 backdrop-blur-xl"><div className="mb-7 flex items-center gap-3 px-2 py-3"><div className="grid h-10 w-10 place-items-center rounded-lg border border-emerald-300/30 bg-emerald-300/10"><Zap className="text-emerald-300" size={20}/></div><div><div className="font-semibold tracking-wide">NekoVerse</div><div className="text-[10px] tracking-[.24em] text-emerald-300/55">COMPANION</div></div></div><nav className="space-y-1">{nav.map(([n,I])=><button key={n} onClick={()=>setPage(n)} className={`flex w-full items-center gap-3 rounded-lg px-3 py-2.5 text-sm transition ${page===n?'border border-emerald-300/20 bg-emerald-300/10 text-emerald-100':'border border-transparent text-white/46 hover:bg-white/[.03] hover:text-white/75'}`}><I size={17}/>{n}</button>)}</nav><div className="absolute bottom-5 left-5 w-[205px] rounded-lg border border-white/6 bg-white/[.018] p-3"><div className="flex items-center gap-2 text-xs text-white/55"><Info size={13} className="text-emerald-300"/> Created by NekoSuneVR</div><div className="mt-1.5 text-[10px] leading-relaxed text-white/28">Unofficial community companion. Not affiliated with CIG/RSI.</div></div></aside><main className="min-w-0 flex-1 overflow-auto"><header className="sticky top-0 z-20 flex h-[74px] items-center justify-between border-b border-emerald-300/10 bg-[#06100b]/85 px-7 backdrop-blur-xl"><div><div className="text-[10px] tracking-[.28em] text-emerald-300/55">NVS // {page.toUpperCase()}</div><div className="mt-1 text-sm text-white/40">STAR CITIZEN COMPANION NETWORK</div></div><div className="flex items-center gap-2"><Badge tone={status?.stale?'amber':'green'}>{status?.stale?'cached':'network online'}</Badge><Badge>{status?.live?`LIVE ${status.live}`:'LIVE —'}</Badge></div></header><div className="p-6">{!hasDesktopBridge()?<Card className="mb-4 p-4 text-sm text-amber-100/70">Browser preview detected. Desktop-only hardware, voice and hotkey functions require Electron.</Card>:null}{busy?<Empty>Booting companion systems…</Empty>:content}</div></main>{toast&&<div className="fixed bottom-5 right-5 z-50 max-w-lg rounded-lg border border-emerald-300/20 bg-[#091710]/95 px-4 py-3 text-sm text-emerald-50 shadow-2xl backdrop-blur-xl">{toast}</div>}</div>
}

function NewsPage({boot,setBoot,notice}){const news=boot?.news;async function refresh(){const n=await api.refreshNews();setBoot(b=>({...b,news:n}));notice('News feed refreshed')}return <div className="space-y-4"><Card className="flex items-center justify-between p-5"><div><div className="text-xs tracking-[.25em] text-emerald-300/60">COMM-LINK FEED</div><div className="mt-1 text-2xl">Latest Star Citizen news</div><div className="mt-1 text-xs text-white/35">{news?.source||'RSI archive adapter'}</div></div><button onClick={refresh} className={`rounded-lg px-3.5 py-2 text-sm ${ghostBtn}`}><RefreshCw size={14} className="mr-2 inline"/>Refresh</button></Card><div className="grid grid-cols-2 gap-3">{news?.items?.map((n,i)=><Card className="p-4" key={n.id||i}><div className="text-xs text-emerald-300/55">{n.published?new Date(n.published).toLocaleDateString():'OFFICIAL FEED'}</div><div className="mt-2 text-lg text-white/85">{n.title}</div>{n.excerpt&&<div className="mt-2 line-clamp-3 text-sm leading-relaxed text-white/42">{n.excerpt}</div>}<div className="mt-3 text-sm"><Open url={n.url}>Read source</Open></div></Card>)}</div></div>}
function Spec({icon:I,label,value}){return <div className="rounded-lg border border-white/6 bg-black/20 p-3"><div className="flex items-center gap-2 text-xs text-white/30"><I size={14} className="text-emerald-300/65"/>{label}</div><div className="mt-2 text-sm text-white/75">{value||'—'}</div></div>}
function Row({k,v}){return <div className="flex items-start justify-between gap-4 border-b border-white/5 pb-2"><dt className="text-white/35">{k}</dt><dd className="max-w-[65%] text-right text-white/70">{v||'—'}</dd></div>}
function Field({label,value,onChange,type='text'}){return <label className="block"><span className="mb-1.5 block text-xs text-white/40">{label}</span><input type={type} value={value} onChange={e=>onChange(e.target.value)} className="w-full rounded-lg border border-emerald-300/15 bg-black/30 px-3 py-2.5 text-sm outline-none focus:border-emerald-300/45"/></label>}
function Check({label,value,onChange}){return <label className="flex items-center gap-2"><input type="checkbox" checked={Boolean(value)} onChange={e=>onChange(e.target.checked)}/>{label}</label>}
