export const languages = [
  { code:'en-GB', name:'English', native:'English' },
  { code:'es-ES', name:'Spanish', native:'Español' },
  { code:'de-DE', name:'German', native:'Deutsch' },
  { code:'pl-PL', name:'Polish', native:'Polski' },
  { code:'ru-RU', name:'Russian', native:'Русский' },
  { code:'fr-FR', name:'French', native:'Français' },
  { code:'it-IT', name:'Italian', native:'Italiano' },
  { code:'pt-PT', name:'Portuguese', native:'Português' }
];

const dict = {
  'en-GB': {
    commandDeck:'Command Deck', assistant:'Assistant', verseGuide:'Verse Guide', news:'News', fleetYards:'FleetYards', marketplace:'Marketplace', optimizer:'Optimizer', settings:'Settings',
    chooseLanguage:'Choose your language', chooseLanguageDesc:'You can change this later in Settings. This also controls Jarvis reply language and the preferred Windows speech-recognition culture.', continue:'Continue',
    voiceAssistant:'Jarvis Assistant', voiceStandby:'Voice standby', listening:'Listening', jarvisActive:'Jarvis active — ask now', activateVoice:'Activate voice', stopListener:'Stop listener',
    directExample:'Say “Jarvis, request landing” or “Jarvis, where is New Babbage?”', stopTalking:'Stop talking', requestLanding:'Request landing',
    updateAvailable:'Update available', runningVersion:'You are running', openUpdate:'Open update', latestVersion:'Latest version', checkNow:'Check now', upToDate:'You are on the latest release',
    language:'Language', wakeWords:'Wake word / assistant name', wakeHelp:'Default is Jarvis. You can change this to a name that is easier for you to pronounce.', requireWake:'Require wake word for voice commands', speakReplies:'Speak assistant replies',
    appUpdates:'Updates', appUpdatesDesc:'Checks GitHub releases at startup and every 5 minutes while the app is running.',
    autoInstall:'Automatic Star Citizen install detection', autoDetected:'Automatically detected', customPath:'Custom Star Citizen install path',
    guideSearch:'Search cities, stations, ores, items, commodities, ships and missions', noMatch:'No exact data match. Check the spelling or try a shorter term.',
    processing:'Processing one request…', askPlaceholder:'Ask about a location, item, ore, ship or command…', save:'Save all settings',
    micOnline:'MIC ONLINE', networkOnline:'network online', cached:'cached', booting:'Booting companion systems…'
  },
  'es-ES': {
    commandDeck:'Panel de mando', assistant:'Asistente', verseGuide:'Guía del Verse', news:'Noticias', fleetYards:'FleetYards', marketplace:'Mercado', optimizer:'Optimizador', settings:'Ajustes',
    chooseLanguage:'Elige tu idioma', chooseLanguageDesc:'Puedes cambiarlo después en Ajustes. También controla el idioma de Jarvis y el idioma preferido del reconocimiento de voz de Windows.', continue:'Continuar',
    voiceAssistant:'Asistente Jarvis', voiceStandby:'Voz en espera', listening:'Escuchando', jarvisActive:'Jarvis activo — pregunta ahora', activateVoice:'Activar voz', stopListener:'Detener escucha',
    directExample:'Di “Jarvis, solicitar aterrizaje” o “Jarvis, ¿dónde está New Babbage?”', stopTalking:'Dejar de hablar', requestLanding:'Solicitar aterrizaje',
    updateAvailable:'Actualización disponible', runningVersion:'Estás usando', openUpdate:'Abrir actualización', latestVersion:'Última versión', checkNow:'Comprobar ahora', upToDate:'Ya tienes la última versión',
    language:'Idioma', wakeWords:'Palabra de activación / nombre del asistente', wakeHelp:'Jarvis es el valor predeterminado. Puedes cambiarlo por un nombre más fácil de pronunciar.', requireWake:'Requerir palabra de activación para comandos de voz', speakReplies:'Leer respuestas en voz alta',
    appUpdates:'Actualizaciones', appUpdatesDesc:'Comprueba GitHub al iniciar y cada 5 minutos mientras la app está abierta.',
    autoInstall:'Detección automática de Star Citizen', autoDetected:'Detectado automáticamente', customPath:'Ruta personalizada de Star Citizen',
    guideSearch:'Buscar ciudades, estaciones, minerales, objetos, mercancías, naves y misiones', noMatch:'No se encontró una coincidencia exacta. Revisa la ortografía o usa un término más corto.',
    processing:'Procesando una solicitud…', askPlaceholder:'Pregunta por una ubicación, objeto, mineral, nave o comando…', save:'Guardar ajustes', micOnline:'MICRÓFONO ACTIVO', networkOnline:'red en línea', cached:'en caché', booting:'Iniciando sistemas…'
  },
  'de-DE': {
    commandDeck:'Kommandodeck', assistant:'Assistent', verseGuide:'Verse-Guide', news:'Neuigkeiten', fleetYards:'FleetYards', marketplace:'Marktplatz', optimizer:'Optimierer', settings:'Einstellungen',
    chooseLanguage:'Sprache wählen', chooseLanguageDesc:'Du kannst sie später in den Einstellungen ändern. Sie steuert auch Jarvis’ Antwortsprache und die bevorzugte Windows-Spracherkennung.', continue:'Weiter',
    voiceAssistant:'Jarvis-Assistent', voiceStandby:'Sprache bereit', listening:'Hört zu', jarvisActive:'Jarvis aktiv — jetzt fragen', activateVoice:'Sprache aktivieren', stopListener:'Zuhören stoppen', directExample:'Sage „Jarvis, Landeerlaubnis anfragen“ oder „Jarvis, wo ist New Babbage?“', stopTalking:'Sprache stoppen', requestLanding:'Landeerlaubnis',
    updateAvailable:'Update verfügbar', runningVersion:'Installiert ist', openUpdate:'Update öffnen', latestVersion:'Neueste Version', checkNow:'Jetzt prüfen', upToDate:'Du hast die neueste Version',
    language:'Sprache', wakeWords:'Aktivierungswort / Assistentenname', wakeHelp:'Standard ist Jarvis. Du kannst einen leichter aussprechbaren Namen wählen.', requireWake:'Aktivierungswort für Sprachbefehle verlangen', speakReplies:'Antworten vorlesen', appUpdates:'Updates', appUpdatesDesc:'Prüft GitHub beim Start und alle 5 Minuten, solange die App läuft.', autoInstall:'Automatische Star-Citizen-Installationserkennung', autoDetected:'Automatisch erkannt', customPath:'Benutzerdefinierter Star-Citizen-Pfad', guideSearch:'Städte, Stationen, Erze, Gegenstände, Waren, Schiffe und Missionen suchen', noMatch:'Keine exakte Übereinstimmung. Prüfe die Schreibweise oder nutze einen kürzeren Begriff.', processing:'Eine Anfrage wird verarbeitet…', askPlaceholder:'Frage nach Ort, Gegenstand, Erz, Schiff oder Befehl…', save:'Einstellungen speichern', micOnline:'MIKROFON AKTIV', networkOnline:'Netzwerk online', cached:'Cache', booting:'Systeme werden gestartet…'
  },
  'pl-PL': {
    commandDeck:'Panel dowodzenia', assistant:'Asystent', verseGuide:'Przewodnik Verse', news:'Aktualności', fleetYards:'FleetYards', marketplace:'Rynek', optimizer:'Optymalizator', settings:'Ustawienia',
    chooseLanguage:'Wybierz język', chooseLanguageDesc:'Możesz go później zmienić w Ustawieniach. Steruje też językiem odpowiedzi Jarvisa i preferowanym językiem rozpoznawania mowy Windows.', continue:'Dalej', voiceAssistant:'Asystent Jarvis', voiceStandby:'Głos w gotowości', listening:'Nasłuchiwanie', jarvisActive:'Jarvis aktywny — zapytaj', activateVoice:'Włącz głos', stopListener:'Zatrzymaj nasłuchiwanie', directExample:'Powiedz „Jarvis, poproś o lądowanie” albo „Jarvis, gdzie jest New Babbage?”', stopTalking:'Przerwij mowę', requestLanding:'Poproś o lądowanie', updateAvailable:'Dostępna aktualizacja', runningVersion:'Używasz wersji', openUpdate:'Otwórz aktualizację', latestVersion:'Najnowsza wersja', checkNow:'Sprawdź teraz', upToDate:'Masz najnowszą wersję', language:'Język', wakeWords:'Słowo aktywujące / nazwa asystenta', wakeHelp:'Domyślnie Jarvis. Możesz wybrać nazwę łatwiejszą do wymówienia.', requireWake:'Wymagaj słowa aktywującego dla poleceń głosowych', speakReplies:'Czytaj odpowiedzi na głos', appUpdates:'Aktualizacje', appUpdatesDesc:'Sprawdza GitHub przy uruchomieniu i co 5 minut podczas działania aplikacji.', autoInstall:'Automatyczne wykrywanie instalacji Star Citizen', autoDetected:'Wykryto automatycznie', customPath:'Niestandardowa ścieżka Star Citizen', guideSearch:'Szukaj miast, stacji, rud, przedmiotów, towarów, statków i misji', noMatch:'Brak dokładnego wyniku. Sprawdź pisownię lub użyj krótszego hasła.', processing:'Przetwarzanie jednego żądania…', askPlaceholder:'Zapytaj o lokalizację, przedmiot, rudę, statek lub polecenie…', save:'Zapisz ustawienia', micOnline:'MIKROFON AKTYWNY', networkOnline:'sieć online', cached:'pamięć podręczna', booting:'Uruchamianie systemów…'
  },
  'ru-RU': {
    commandDeck:'Командная панель', assistant:'Ассистент', verseGuide:'Гид по Verse', news:'Новости', fleetYards:'FleetYards', marketplace:'Маркет', optimizer:'Оптимизатор', settings:'Настройки',
    chooseLanguage:'Выберите язык', chooseLanguageDesc:'Позже язык можно изменить в Настройках. Он также задаёт язык ответов Jarvis и предпочтительный язык распознавания речи Windows.', continue:'Продолжить', voiceAssistant:'Ассистент Jarvis', voiceStandby:'Голос в ожидании', listening:'Слушаю', jarvisActive:'Jarvis активен — задавайте вопрос', activateVoice:'Включить голос', stopListener:'Остановить прослушивание', directExample:'Скажите «Jarvis, запроси посадку» или «Jarvis, где находится New Babbage?»', stopTalking:'Замолчать', requestLanding:'Запросить посадку', updateAvailable:'Доступно обновление', runningVersion:'Установлена версия', openUpdate:'Открыть обновление', latestVersion:'Последняя версия', checkNow:'Проверить сейчас', upToDate:'У вас последняя версия', language:'Язык', wakeWords:'Ключевое слово / имя ассистента', wakeHelp:'По умолчанию Jarvis. Можно выбрать имя, которое легче произносить.', requireWake:'Требовать ключевое слово для голосовых команд', speakReplies:'Озвучивать ответы', appUpdates:'Обновления', appUpdatesDesc:'Проверяет GitHub при запуске и каждые 5 минут во время работы приложения.', autoInstall:'Автоматический поиск Star Citizen', autoDetected:'Найдено автоматически', customPath:'Пользовательский путь Star Citizen', guideSearch:'Искать города, станции, руды, предметы, товары, корабли и миссии', noMatch:'Точного совпадения нет. Проверьте написание или используйте более короткий запрос.', processing:'Обрабатывается один запрос…', askPlaceholder:'Спросите о месте, предмете, руде, корабле или команде…', save:'Сохранить настройки', micOnline:'МИКРОФОН ВКЛ', networkOnline:'сеть доступна', cached:'кэш', booting:'Запуск систем…'
  },
  'fr-FR': {
    commandDeck:'Poste de commande', assistant:'Assistant', verseGuide:'Guide du Verse', news:'Actualités', fleetYards:'FleetYards', marketplace:'Marché', optimizer:'Optimiseur', settings:'Paramètres', chooseLanguage:'Choisissez votre langue', chooseLanguageDesc:'Vous pourrez la modifier plus tard. Elle contrôle aussi la langue de réponse de Jarvis et la langue préférée de reconnaissance vocale Windows.', continue:'Continuer', voiceAssistant:'Assistant Jarvis', voiceStandby:'Voix en attente', listening:'Écoute', jarvisActive:'Jarvis actif — posez votre question', activateVoice:'Activer la voix', stopListener:'Arrêter l’écoute', directExample:'Dites « Jarvis, demande l’atterrissage » ou « Jarvis, où est New Babbage ? »', stopTalking:'Arrêter de parler', requestLanding:'Demander l’atterrissage', updateAvailable:'Mise à jour disponible', runningVersion:'Version installée', openUpdate:'Ouvrir la mise à jour', latestVersion:'Dernière version', checkNow:'Vérifier', upToDate:'Vous avez la dernière version', language:'Langue', wakeWords:'Mot d’activation / nom de l’assistant', wakeHelp:'Jarvis par défaut. Vous pouvez choisir un nom plus facile à prononcer.', requireWake:'Exiger le mot d’activation pour les commandes vocales', speakReplies:'Lire les réponses', appUpdates:'Mises à jour', appUpdatesDesc:'Vérifie GitHub au démarrage puis toutes les 5 minutes.', autoInstall:'Détection automatique de Star Citizen', autoDetected:'Détecté automatiquement', customPath:'Chemin Star Citizen personnalisé', guideSearch:'Rechercher villes, stations, minerais, objets, marchandises, vaisseaux et missions', noMatch:'Aucun résultat exact. Vérifiez l’orthographe ou utilisez un terme plus court.', processing:'Traitement d’une requête…', askPlaceholder:'Posez une question sur un lieu, objet, minerai, vaisseau ou commande…', save:'Enregistrer', micOnline:'MICRO ACTIF', networkOnline:'réseau en ligne', cached:'cache', booting:'Démarrage des systèmes…'
  },
  'it-IT': {
    commandDeck:'Ponte di comando', assistant:'Assistente', verseGuide:'Guida Verse', news:'Notizie', fleetYards:'FleetYards', marketplace:'Mercato', optimizer:'Ottimizzatore', settings:'Impostazioni', chooseLanguage:'Scegli la lingua', chooseLanguageDesc:'Puoi cambiarla in seguito. Controlla anche la lingua delle risposte di Jarvis e la lingua preferita del riconoscimento vocale di Windows.', continue:'Continua', voiceAssistant:'Assistente Jarvis', voiceStandby:'Voce in attesa', listening:'In ascolto', jarvisActive:'Jarvis attivo — chiedi ora', activateVoice:'Attiva voce', stopListener:'Ferma ascolto', directExample:'Di’ “Jarvis, richiedi atterraggio” o “Jarvis, dov’è New Babbage?”', stopTalking:'Interrompi voce', requestLanding:'Richiedi atterraggio', updateAvailable:'Aggiornamento disponibile', runningVersion:'Versione in uso', openUpdate:'Apri aggiornamento', latestVersion:'Ultima versione', checkNow:'Controlla ora', upToDate:'Hai già l’ultima versione', language:'Lingua', wakeWords:'Parola di attivazione / nome assistente', wakeHelp:'Jarvis è il valore predefinito. Puoi scegliere un nome più facile da pronunciare.', requireWake:'Richiedi parola di attivazione per i comandi vocali', speakReplies:'Leggi le risposte', appUpdates:'Aggiornamenti', appUpdatesDesc:'Controlla GitHub all’avvio e ogni 5 minuti.', autoInstall:'Rilevamento automatico di Star Citizen', autoDetected:'Rilevato automaticamente', customPath:'Percorso Star Citizen personalizzato', guideSearch:'Cerca città, stazioni, minerali, oggetti, merci, navi e missioni', noMatch:'Nessuna corrispondenza esatta. Controlla l’ortografia o prova un termine più breve.', processing:'Elaborazione di una richiesta…', askPlaceholder:'Chiedi di un luogo, oggetto, minerale, nave o comando…', save:'Salva impostazioni', micOnline:'MICROFONO ATTIVO', networkOnline:'rete online', cached:'cache', booting:'Avvio sistemi…'
  },
  'pt-PT': {
    commandDeck:'Painel de comando', assistant:'Assistente', verseGuide:'Guia do Verse', news:'Notícias', fleetYards:'FleetYards', marketplace:'Mercado', optimizer:'Otimizador', settings:'Definições', chooseLanguage:'Escolha o idioma', chooseLanguageDesc:'Pode alterá-lo mais tarde. Também controla o idioma das respostas do Jarvis e o idioma preferido do reconhecimento de voz do Windows.', continue:'Continuar', voiceAssistant:'Assistente Jarvis', voiceStandby:'Voz em espera', listening:'A ouvir', jarvisActive:'Jarvis ativo — pergunte agora', activateVoice:'Ativar voz', stopListener:'Parar escuta', directExample:'Diga “Jarvis, pedir aterragem” ou “Jarvis, onde fica New Babbage?”', stopTalking:'Parar de falar', requestLanding:'Pedir aterragem', updateAvailable:'Atualização disponível', runningVersion:'Está a usar', openUpdate:'Abrir atualização', latestVersion:'Última versão', checkNow:'Verificar agora', upToDate:'Já tem a versão mais recente', language:'Idioma', wakeWords:'Palavra de ativação / nome do assistente', wakeHelp:'Jarvis por defeito. Pode escolher um nome mais fácil de pronunciar.', requireWake:'Exigir palavra de ativação para comandos de voz', speakReplies:'Ler respostas em voz alta', appUpdates:'Atualizações', appUpdatesDesc:'Verifica o GitHub ao iniciar e a cada 5 minutos enquanto a aplicação estiver aberta.', autoInstall:'Deteção automática de Star Citizen', autoDetected:'Detetado automaticamente', customPath:'Caminho personalizado do Star Citizen', guideSearch:'Pesquisar cidades, estações, minérios, itens, mercadorias, naves e missões', noMatch:'Sem correspondência exata. Verifique a ortografia ou tente um termo mais curto.', processing:'A processar um pedido…', askPlaceholder:'Pergunte por um local, item, minério, nave ou comando…', save:'Guardar definições', micOnline:'MICROFONE ATIVO', networkOnline:'rede online', cached:'cache', booting:'A iniciar sistemas…'
  }
};

export function tr(locale, key) {
  return dict[locale]?.[key] || dict['en-GB'][key] || key;
}

export function languageName(locale) {
  return languages.find(l=>l.code===locale)?.native || locale;
}
